"""LibreWolf configuration patch -- Az'arch browser policy overrides.

LibreWolf is an UPSTREAM privacy-hardened Firefox fork we ship (built by the
recipe in packages/pkgbuild.py). We do not fork it; we only OVERRIDE a handful of
its defaults to fit Az'arch. That override policy lives HERE (a patch-package,
like calamares/ckbcomp/fastfetch/openbox) so it is the single source of truth:
packages/pkgbuild.py imports overrides_cfg() and ships the returned text as
/opt/librewolf/librewolf.overrides.cfg -- LibreWolf's officially-supported
AutoConfig override file, loaded AFTER the stock librewolf.cfg
(https://librewolf.net/docs/settings/), so a defaultPref here beats LibreWolf's
own defaultPref for the same key.

Everything else is stock LibreWolf. We change exactly two things (both requested):

  1. SESSION + COOKIE PERSISTENCE. LibreWolf ships privacy-hardened and, by
     default, wipes cookies + history on shutdown (privacy.sanitize.
     sanitizeOnShutdown = true) and does NOT restore the previous window/tabs.
     Az'arch wants logins and open tabs to SURVIVE a restart, so we:
       * turn off shutdown sanitisation (the master switch), and belt-and-braces
         clear the per-category clearOnShutdown_v2 cookie flag;
       * restore the previous session on startup (browser.startup.page = 3);
       * set browser.sessionstore.privacy_level = 0. THIS ONE IS LOAD-BEARING and
         easy to miss: LibreWolf defaults it to 2 ("save no session data for any
         site"), which keeps the session store URL-only and drops the cookies /
         form data a real "restore previous session" needs -- so with the stock
         value the tabs come back logged OUT. 0 is the Firefox default (store
         everything) and is LibreWolf's own documented fix for pinned-tab /
         session loss. Without it, sanitizeOnShutdown=false alone is not enough.
     We deliberately do NOT set network.cookie.lifetimePolicy: that pref is
     OBSOLETE in modern Firefox/LibreWolf (the engine migrates it away and
     ClearUser()s it on startup), so writing it does nothing useful. Keeping
     sanitizeOnShutdown = false IS the modern "cookies persist" mechanism.

  2. HIDE THE BOOKMARKS TOOLBAR ("For quick access"). LibreWolf overrides the
     Firefox default and ships browser.toolbars.bookmarks.visibility = "always",
     so the bookmarks toolbar (the "For quick access, place your bookmarks here"
     strip below the address bar; Ctrl+Shift+B) shows on every window by default.
     Az'arch wants it hidden by default, so we set it to "never" (the value that
     hides it on every window AND the new-tab page; the other values are "always"
     and "newtab"). The user can still toggle it back on with Ctrl+Shift+B.

Only relaxes/sets these specific prefs; every other LibreWolf hardening pref is
left exactly as upstream ships it. Pure standard library (returns a string);
compiler.py never touches this module directly -- pkgbuild.py does, at recipe
emit time.
"""

from __future__ import annotations


# The AutoConfig override filename the recipe installs under /opt/librewolf.
# LibreWolf reads this after librewolf.cfg (its general.config.filename), so a
# defaultPref here overrides LibreWolf's own defaultPref for the same key.
OVERRIDES_FILENAME = "librewolf.overrides.cfg"


def overrides_cfg() -> str:
    """Return the full text of librewolf.overrides.cfg (see the module docstring).

    Two policies: (1) sessions + cookies persist across restarts, (2) the
    bookmarks toolbar ("For quick access") is hidden by default. This is the
    single source of truth; packages/pkgbuild.py ships it verbatim.

    AutoConfig files MUST begin with a comment line -- the engine ignores line 1
    -- so the leading `//` banner is required, not decoration."""
    return """\
// Az'arch LibreWolf overrides -- session/cookie persistence + hidden bookmarks bar
//
// LibreWolf's officially-supported override file (general.config.filename),
// loaded AFTER the stock librewolf.cfg, so a defaultPref here beats LibreWolf's
// own defaultPref for the same key. Generated by patches/librewolf/librewolf.py
// (edit the Python, not this file). It ONLY changes the prefs below; every other
// LibreWolf hardening pref is left exactly as upstream ships it.
//
// AutoConfig files must begin with a comment line; the engine ignores line 1.

// === 1. Sessions & cookies persist across restarts ========================
// LibreWolf wipes cookies + history on shutdown and does not restore tabs by
// default; Az'arch wants logins and open tabs to survive a restart.

// --- Master switch: do not sanitise anything on shutdown -------------------
defaultPref("privacy.sanitize.sanitizeOnShutdown", false);

// --- Belt-and-braces: keep cookies/storage even if a shutdown clear ran ----
// (Moot while sanitizeOnShutdown is false, but explicit and harmless. The _v2
// keys are the modern namespace; the pre-128 privacy.clearOnShutdown.* keys are
// legacy/dead once migrated, so we do not set them.)
defaultPref("privacy.clearOnShutdown_v2.cookiesAndStorage", false);

// --- Restore the previous session on start, so open tabs come back ---------
defaultPref("browser.startup.page", 3);

// --- LOAD-BEARING: let the session store keep cookies/form data ------------
// LibreWolf defaults browser.sessionstore.privacy_level to 2 ("save no session
// data for any site"), which makes the restored session URL-only -- tabs come
// back LOGGED OUT. 0 (the Firefox default: store everything) is required for a
// real "restore previous session", and is LibreWolf's own documented fix for
// pinned-tab/session loss. Without this, sanitizeOnShutdown=false is not enough.
defaultPref("browser.sessionstore.privacy_level", 0);

// === 2. Hide the bookmarks toolbar ("For quick access") by default =========
// LibreWolf ships this as "always"; Az'arch wants the "For quick access, place
// your bookmarks here on the bookmarks toolbar" strip (Ctrl+Shift+B) hidden by
// default. "never" hides it on every window AND the new-tab page. The user can
// still toggle it back on with Ctrl+Shift+B. (Values: "always"/"newtab"/"never".)
defaultPref("browser.toolbars.bookmarks.visibility", "never");
"""
