"""Az'arch OWN package recipes, authored as config-as-Python.

Everything the ISO installs that is NOT in the official Arch repositories is
built from recipes WE write and maintain here -- never from the AUR or any
community source. Like the rest of azarch.config, each artifact (the PKGBUILDs
and their companion files) is held as a Python string and emitted into the build
tree by steps.py; the emitted files are then consumed by `makepkg`, the official
Arch build tool, which produces *.pkg.tar.zst dropped into the ISO's offline
repo. No AUR helper (yay/paru/...) is used.

Two packages are built:

  calamares   -- the graphical system installer (Manjaro-style). ALWAYS compiled
                 from source (a moderate C++/CMake build, minutes not hours), so
                 both build tiers produce it identically.

  librewolf   -- the privacy-hardened Firefox fork. A from-source Firefox build
                 takes 1.5-3+ hours and ~16 GB RAM, so there are TWO recipes:
                   * DEFAULT tier (`compile.sh`)          -> pkgbuild_librewolf()
                     repackages LibreWolf's official prebuilt tarball, verified by
                     BOTH a pinned sha256 AND its OpenPGP signature.
                   * FULL tier   (`compile.sh --full-compile`) -> pkgbuild_librewolf_src()
                     compiles LibreWolf from Firefox source via LibreWolf's bsys6
                     build harness.
                 recipe_dirs(full_compile) picks which pair of recipes to emit.

Pinned upstream facts (versions, URLs, checksums, signing key) live as the
constants below -- the single source of truth. All checksums were obtained by
downloading the real artifacts and hashing them, and are re-checked by makepkg
at build time (it aborts on mismatch). See update notes at the bottom.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Pinned upstream facts (single source of truth)
# ---------------------------------------------------------------------------
CALAMARES_VERSION = "3.4.2"
# sha256 of the official release tarball, obtained by download + sha256sum.
CALAMARES_SHA256 = "733bbbb00dc9f84874bd5c22960952f317ea2537565431179fa2152b2fbfdccc"

# LibreWolf: upstream tag is "153.0-1"; pacman-legal pkgver is "153.0.1".
LIBREWOLF_VERSION = "153.0-1"
LIBREWOLF_PKGVER = "153.0.1"
# sha256 from upstream's published .sha256sum, re-verified by download + hash.
LIBREWOLF_SHA256 = "ca15edcb35e4af09ce59725f0ee28c6e9fcf7fc25367e540583b8c2c862c0df7"
# LibreWolf release signing key -- the PRIMARY key fingerprint of
# "LibreWolf Maintainers <gpg@librewolf.net>". makepkg's validpgpkeys=() must list
# the PRIMARY key, NOT the signing subkey: the tarball's detached .sig is made by
# an ed25519 *subkey* (915585A1C36690B1 / 230FE8E0...C36690B1), and makepkg maps a
# signing subkey back to its primary and requires THAT primary to be in
# validpgpkeys. Pinning the subkey fingerprint here made makepkg abort with
# "invalid public key 662E3CDD...2B12EF16" (the primary it actually needs). Verify
# on update: `gpg --list-packets <tarball>.sig` shows the signing subkey keyid;
# `gpg --recv-keys <that keyid>` then shows the primary under `pub`.
LIBREWOLF_PGP_KEY = "662E3CDD6FE329002D0CA5BB40339DD82B12EF16"


# ---------------------------------------------------------------------------
# calamares -- built from source, always
# ---------------------------------------------------------------------------
def pkgbuild_calamares() -> str:
    return f"""\
# Maintainer: Az'arch <https://github.com/michaelilgiaev/azarch>
#
# =============================================================================
# Az'arch OWN PKGBUILD -- calamares  (generated by azarch.config.pkgbuild)
# =============================================================================
# NOT a community/AUR recipe. Written + maintained by the Az'arch project so the
# build has no dependency on third-party packaging.
#
# Calamares is the distribution-independent graphical system installer. Az'arch
# uses it as the live-ISO installer (Manjaro-style), configured for a Btrfs
# default and optional full-disk LUKS encryption via module configs shipped on
# the ISO (this recipe only builds the binary).
#
# SOURCE (fully auditable):
#   Project : https://codeberg.org/Calamares/calamares
#   Release : https://codeberg.org/Calamares/calamares/releases/tag/v{CALAMARES_VERSION}
#   Tarball : https://codeberg.org/Calamares/calamares/releases/download/v{CALAMARES_VERSION}/calamares-{CALAMARES_VERSION}.tar.gz
#   License : GPL-3.0-or-later
#
# INTEGRITY: pinned sha256 below (from download + sha256sum). Upstream ships no
# detached .sig for the release archive, so the sha256 is the anchor; makepkg
# aborts the build on mismatch.
#
# ALWAYS FROM SOURCE: a moderate C++/CMake build (minutes), so both the default
# and --full-compile Az'arch tiers compile it identically.
# =============================================================================

pkgname=calamares
pkgver={CALAMARES_VERSION}
pkgrel=1
pkgdesc="Distribution-independent installer framework (Az'arch build)"
arch=('x86_64')
url="https://codeberg.org/Calamares/calamares"
license=('GPL-3.0-or-later')

# Deps per upstream CMakeLists.txt for the 3.4.x line: Qt6 >= 6.5, KF6 >= 6.5,
# ECM 6.5, CMake >= 3.16, yaml-cpp, kpmcore (partitioning), polkit-qt6, boost +
# bundled pybind11 (Python job modules), squashfs-tools/rsync (unpackfs), plus
# the filesystem tools the partition module drives.
depends=(
  'qt6-base' 'qt6-svg' 'qt6-declarative'
  'kcoreaddons' 'kconfig' 'ki18n' 'kcrash'
  'kpmcore' 'yaml-cpp' 'polkit-qt6' 'boost-libs'
  'python' 'squashfs-tools' 'rsync'
  'cryptsetup' 'dosfstools' 'e2fsprogs' 'btrfs-progs' 'gptfdisk'
  'hwinfo' 'icu'
)
makedepends=('cmake' 'extra-cmake-modules' 'qt6-tools' 'boost' 'git')
optdepends=(
  'btrfs-progs: Btrfs filesystem support'
  'cryptsetup: full-disk LUKS encryption support'
  'grub: GRUB bootloader install'
)

source=("calamares-${{pkgver}}.tar.gz::${{url}}/releases/download/v${{pkgver}}/calamares-${{pkgver}}.tar.gz")
sha256sums=('{CALAMARES_SHA256}')

build() {{
  cd "calamares-${{pkgver}}"
  # Qt6 + KF6, bundled pybind11 for Python job modules, QML on for the branding
  # slideshow, crash reporter off (extra deps, pointless on a live ISO).
  cmake -B build -S . \\
    -DCMAKE_BUILD_TYPE=Release \\
    -DCMAKE_INSTALL_PREFIX=/usr \\
    -DCMAKE_INSTALL_LIBDIR=lib \\
    -DWITH_QT6=ON \\
    -DWITH_PYBIND11=ON \\
    -DWITH_QML=ON \\
    -DBUILD_CRASH_REPORTING=OFF \\
    -DINSTALL_POLKIT=ON \\
    -DWEBVIEW_FORCE_WEBKIT=OFF
  cmake --build build
}}

package() {{
  cd "calamares-${{pkgver}}"
  DESTDIR="$pkgdir" cmake --install build
}}
"""


# ---------------------------------------------------------------------------
# librewolf -- shared companion files (used by BOTH tiers)
# ---------------------------------------------------------------------------
def librewolf_desktop() -> str:
    return """\
[Desktop Entry]
Name=LibreWolf
GenericName=Web Browser
Comment=Browse the web (Az'arch build, sessions/cookies persist)
Exec=/opt/librewolf/librewolf %u
Icon=librewolf
Terminal=false
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
StartupWMClass=librewolf
Categories=Network;WebBrowser;
Keywords=Internet;WWW;Browser;Web;Explorer;
Actions=new-window;new-private-window;

[Desktop Action new-window]
Name=Open a New Window
Exec=/opt/librewolf/librewolf --new-window %u

[Desktop Action new-private-window]
Name=Open a New Private Window
Exec=/opt/librewolf/librewolf --private-window %u
"""


def librewolf_overrides_cfg() -> str:
    """LibreWolf's officially-supported override file (loaded AFTER the stock
    librewolf.cfg). Relaxes ONLY the sanitise-on-shutdown prefs so sessions and
    cookies persist; every other LibreWolf hardening pref is left as upstream
    ships it. https://librewolf.net/docs/settings/"""
    return """\
// Az'arch LibreWolf overrides -- session & cookie persistence
//
// LibreWolf ships privacy-hardened and by DEFAULT wipes cookies + history on
// shutdown (privacy.sanitize.sanitizeOnShutdown = true, plus the clearOnShutdown
// keys). Az'arch wants sessions and logins to PERSIST across restarts, so this
// file -- LibreWolf's officially-supported override, loaded AFTER librewolf.cfg
// -- turns that behaviour off. It ONLY relaxes the shutdown-sanitisation prefs;
// every other LibreWolf hardening pref is left exactly as upstream ships it.
//
// AutoConfig files must begin with a comment line; the engine ignores line 1.

// --- Do not sanitise on shutdown ------------------------------------------
defaultPref("privacy.sanitize.sanitizeOnShutdown", false);

// --- Keep each data category on shutdown (new _v2 keys, FF/LW current) -----
defaultPref("privacy.clearOnShutdown_v2.cookiesAndStorage", false);
defaultPref("privacy.clearOnShutdown_v2.historyFormDataAndDownloads", false);
defaultPref("privacy.clearOnShutdown_v2.browsingHistoryAndDownloads", false);
defaultPref("privacy.clearOnShutdown_v2.cache", false);
defaultPref("privacy.clearOnShutdown_v2.siteSettings", false);
defaultPref("privacy.clearOnShutdown_v2.formdata", false);

// --- Legacy keys (older builds still honour these) -------------------------
defaultPref("privacy.clearOnShutdown.cookies", false);
defaultPref("privacy.clearOnShutdown.history", false);
defaultPref("privacy.clearOnShutdown.sessions", false);
defaultPref("privacy.clearOnShutdown.cache", false);
defaultPref("privacy.clearOnShutdown.offlineApps", false);
defaultPref("privacy.clearOnShutdown.formdata", false);
defaultPref("privacy.clearOnShutdown.siteSettings", false);

// --- Cookies live their normal lifetime (0 = accept normally) --------------
defaultPref("network.cookie.lifetimePolicy", 0);

// --- Restore the previous session on start, so open tabs come back ---------
defaultPref("browser.startup.page", 3);
"""


# ---------------------------------------------------------------------------
# librewolf -- DEFAULT tier (repackage the verified upstream tarball)
# ---------------------------------------------------------------------------
def pkgbuild_librewolf() -> str:
    dl = f"https://dl.librewolf.net/librewolf/{LIBREWOLF_VERSION}"
    tar = f"librewolf-{LIBREWOLF_VERSION}-linux-x86_64-package.tar.xz"
    return f"""\
# Maintainer: Az'arch <https://github.com/michaelilgiaev/azarch>
#
# =============================================================================
# Az'arch OWN PKGBUILD -- librewolf (DEFAULT tier: repackage verified upstream)
# =============================================================================
# NOT a community/AUR recipe. Written + maintained by the Az'arch project.
# Generated by azarch.config.pkgbuild.
#
# A from-source LibreWolf/Firefox compile takes 1.5-3+ hours and needs ~16 GB
# RAM. To keep the DEFAULT `compile.sh` build fast, this recipe repackages
# LibreWolf's OFFICIAL prebuilt generic-Linux tarball, verified TWO ways:
#   1. pinned sha256sum (from upstream's published .sha256sum), and
#   2. detached OpenPGP signature (.sig) against the LibreWolf release key.
# For an all-self-compiled build use `compile.sh --full-compile`, which selects
# the source recipe instead.
#
# SOURCE (fully auditable):
#   Build system : https://codeberg.org/librewolf/bsys6
#   Website      : https://librewolf.net/
#   Tarball      : {dl}/{tar}
#   Signature    : {dl}/{tar}.sig   (key {LIBREWOLF_PGP_KEY})
#   Checksum src : {dl}/{tar}.sha256sum
#   License      : MPL-2.0
# The tarball is built by LibreWolf from Firefox source + LibreWolf's public
# patch set, so the lineage traces to scrutinizable source even in this path.
#
# AZ'ARCH CUSTOMISATION: LibreWolf clears cookies + history on shutdown by
# default; Az'arch ships librewolf.overrides.cfg (LibreWolf's supported override)
# so sessions and cookies persist. Everything else is stock LibreWolf.
# =============================================================================

pkgname=librewolf
pkgver={LIBREWOLF_PKGVER}
_lwver={LIBREWOLF_VERSION}
pkgrel=1
pkgdesc="Privacy-hardened Firefox fork, session/cookie persistence (Az'arch build)"
arch=('x86_64')
url="https://librewolf.net/"
license=('MPL-2.0')
depends=('gtk3' 'libxt' 'mime-types' 'dbus' 'ffmpeg' 'nss' 'ttf-font'
         'libpulse' 'libnotify' 'pciutils')
options=('!strip')

_dl="{dl}"
source=(
  "librewolf-${{_lwver}}-linux-x86_64-package.tar.xz::${{_dl}}/librewolf-${{_lwver}}-linux-x86_64-package.tar.xz"
  "librewolf-${{_lwver}}-linux-x86_64-package.tar.xz.sig::${{_dl}}/librewolf-${{_lwver}}-linux-x86_64-package.tar.xz.sig"
  'librewolf.desktop'
  'librewolf.overrides.cfg'
)
# Tarball: pinned sha256 (+ GPG). .sig: GPG-checked (SKIP sha). Local files:
# shipped in-repo, reviewed in azarch.config.pkgbuild (SKIP sha).
sha256sums=('{LIBREWOLF_SHA256}' 'SKIP' 'SKIP' 'SKIP')
validpgpkeys=('{LIBREWOLF_PGP_KEY}')

package() {{
  # Tarball extracts to a top-level librewolf/ dir (Firefox-style layout).
  install -d "$pkgdir/opt"
  cp -a "$srcdir/librewolf" "$pkgdir/opt/librewolf"

  install -d "$pkgdir/usr/bin"
  ln -s /opt/librewolf/librewolf "$pkgdir/usr/bin/librewolf"

  install -Dm644 "$srcdir/librewolf.desktop" \\
    "$pkgdir/usr/share/applications/librewolf.desktop"

  local icon="$srcdir/librewolf/browser/chrome/icons/default/default128.png"
  [[ -f "$icon" ]] && install -Dm644 "$icon" \\
    "$pkgdir/usr/share/icons/hicolor/128x128/apps/librewolf.png"

  # Az'arch persistence override (loaded after the stock librewolf.cfg).
  install -Dm644 "$srcdir/librewolf.overrides.cfg" \\
    "$pkgdir/opt/librewolf/librewolf.overrides.cfg"
}}
"""


# ---------------------------------------------------------------------------
# librewolf -- FULL tier (compile from Firefox source via bsys6)
# ---------------------------------------------------------------------------
def pkgbuild_librewolf_src() -> str:
    return f"""\
# Maintainer: Az'arch <https://github.com/michaelilgiaev/azarch>
#
# =============================================================================
# Az'arch OWN PKGBUILD -- librewolf (FULL-COMPILE tier: build from source)
# =============================================================================
# NOT a community/AUR recipe. Written + maintained by the Az'arch project.
# Generated by azarch.config.pkgbuild. Selected ONLY by `compile.sh --full-compile`.
#
# ///////////////////////////////////////////////////////////////////////////
#  HEAVY BUILD WARNING: a from-source LibreWolf/Firefox compile takes 1.5-3+
#  hours on a strong multi-core machine and needs ~16 GB RAM + tens of GB disk.
#  The default `compile.sh` (repackage tier) exists to avoid this.
# ///////////////////////////////////////////////////////////////////////////
#
# SOURCE (fully auditable):
#   Build system : https://codeberg.org/librewolf/bsys6   (tag {LIBREWOLF_VERSION})
#   which fetches Mozilla Firefox source (release 153.0) + LibreWolf's public
#   patch set/settings, all in the codeberg repos.
#   License      : MPL-2.0
#
# INTEGRITY: bsys6 verifies the Firefox source it downloads against Mozilla's
# published checksums as part of its own build. We pin bsys6 by git tag.
# =============================================================================

pkgname=librewolf
pkgver={LIBREWOLF_PKGVER}
_lwver={LIBREWOLF_VERSION}
pkgrel=1
pkgdesc="Privacy-hardened Firefox fork built FROM SOURCE, persistence (Az'arch build)"
arch=('x86_64')
url="https://librewolf.net/"
license=('MPL-2.0')
depends=('gtk3' 'libxt' 'mime-types' 'dbus' 'ffmpeg' 'nss' 'ttf-font'
         'libpulse' 'libnotify' 'pciutils')
# The Firefox build toolchain -- the bulk of what makes the full compile heavy.
makedepends=('rust' 'clang' 'llvm' 'lld' 'nodejs' 'cbindgen' 'nasm' 'yasm'
             'python' 'python-setuptools' 'unzip' 'zip' 'gawk' 'perl' 'wget'
             'mercurial' 'git' 'make' 'pkgconf' 'gtk3' 'nss' 'gcc' 'which'
             'mesa' 'libpulse' 'dbus-glib' 'alsa-lib')
options=('!strip' '!lto' '!debug')

source=(
  "librewolf-bsys6::git+https://codeberg.org/librewolf/bsys6.git#tag=${{_lwver}}"
  'librewolf.desktop'
  'librewolf.overrides.cfg'
)
sha256sums=('SKIP' 'SKIP' 'SKIP')

build() {{
  cd "$srcdir/librewolf-bsys6"
  # bsys6's documented top-level targets: fetch Firefox source + LibreWolf
  # patches/settings, build, then produce the generic-linux package tree.
  make fetch
  make build
  make package
}}

package() {{
  cd "$srcdir/librewolf-bsys6"
  # Locate the produced package tree / tarball (bsys6 emits under its own dir).
  local tree
  tree="$(find . -maxdepth 4 -type d -name librewolf -path '*obj*' 2>/dev/null | head -1)"
  if [[ -z "$tree" ]]; then
    local tarball
    tarball="$(find . -maxdepth 3 -name 'librewolf-*.tar.xz' 2>/dev/null | head -1)"
    [[ -n "$tarball" ]] || {{ echo "librewolf-src: could not locate build output"; return 1; }}
    bsdtar -xf "$tarball" -C "$srcdir"
    tree="$srcdir/librewolf"
  fi

  install -d "$pkgdir/opt"
  cp -a "$tree" "$pkgdir/opt/librewolf"

  install -d "$pkgdir/usr/bin"
  ln -s /opt/librewolf/librewolf "$pkgdir/usr/bin/librewolf"

  install -Dm644 "$srcdir/librewolf.desktop" \\
    "$pkgdir/usr/share/applications/librewolf.desktop"

  local icon="$pkgdir/opt/librewolf/browser/chrome/icons/default/default128.png"
  [[ -f "$icon" ]] && install -Dm644 "$icon" \\
    "$pkgdir/usr/share/icons/hicolor/128x128/apps/librewolf.png"

  install -Dm644 "$srcdir/librewolf.overrides.cfg" \\
    "$pkgdir/opt/librewolf/librewolf.overrides.cfg"
}}
"""


# ---------------------------------------------------------------------------
# Recipe emission plan: (dirname, {filename: content}) tuples.
# steps.py iterates this to write each recipe dir into the build tree, then the
# makepkg stage builds each and drops the result into the offline repo.
# ---------------------------------------------------------------------------
def recipe_dirs(full_compile: bool) -> list[tuple[str, dict[str, str]]]:
    """Which recipes to emit. Calamares always; librewolf source depends on tier."""
    lw_common = {
        "librewolf.desktop": librewolf_desktop(),
        "librewolf.overrides.cfg": librewolf_overrides_cfg(),
    }
    calamares = ("calamares", {"PKGBUILD": pkgbuild_calamares()})
    if full_compile:
        librewolf = ("librewolf", {"PKGBUILD": pkgbuild_librewolf_src(), **lw_common})
    else:
        librewolf = ("librewolf", {"PKGBUILD": pkgbuild_librewolf(), **lw_common})
    return [calamares, librewolf]


# ---------------------------------------------------------------------------
# Updating versions:
#   1. Bump CALAMARES_VERSION / LIBREWOLF_VERSION / LIBREWOLF_PKGVER above.
#   2. Refresh the pinned sha256 constants from upstream's published checksum
#      (librewolf: .../<ver>/librewolf-<ver>-linux-x86_64-package.tar.xz.sha256sum).
#   3. If LibreWolf rotates its signing key, update LIBREWOLF_PGP_KEY.
#   4. Rebuild with FORCE_ONLINE=1 so the new sources are fetched.
# ---------------------------------------------------------------------------
