"""profiledef.sh -- the archiso profile definition mkarchiso sources.

mkarchiso REQUIRES this to be a bash script it can `source` (it reads iso_name,
bootmodes, file_permissions, etc. as shell variables), so we can't make it Python.
Instead we AUTHOR it in Python (the values live in a dict/list here) and emit the
bash file. That keeps the source of truth in Python like everything else.

Notably this carries the zstd squashfs workaround for the sporadic
"xz uncompress failed with error code 9" and the file_permissions map that locks
down shadow/gshadow/sudoers in the ISO.
"""

from __future__ import annotations

ISO_NAME = "azarch"
ISO_PUBLISHER = "michaelilgiaev <https://github.com/michaelilgiaev/azarch>"
ISO_APPLICATION = "Az'arch Installer/Az'arch Linux Live/Rescue DVD"
INSTALL_DIR = "arch"

BOOTMODES = (
    "bios.syslinux.mbr",
    "bios.syslinux.eltorito",
    "uefi-ia32.systemd-boot.esp",
    "uefi-x64.systemd-boot.esp",
    "uefi-ia32.systemd-boot.eltorito",
    "uefi-x64.systemd-boot.eltorito",
)

# path -> "owner:group:octal" baked into the squashfs by mkarchiso.
FILE_PERMISSIONS = {
    "/etc/shadow": "0:0:400",
    "/etc/gshadow": "0:0:400",
    # sudoers drop-ins: archiso normalizes overlay modes, so pin these to 0440
    # (the sudo convention) rather than letting them ship 0644. steps.py emits
    # them 0440 but that mode is lost in the squashfs without an entry here.
    "/etc/sudoers.d/00-main": "0:0:440",
    "/etc/sudoers.d/00-rootpw": "0:0:440",
    "/root": "0:0:750",
    "/root/azarch": "0:0:750",
    "/root/.automated_script.sh": "0:0:755",
    "/root/.gnupg": "0:0:700",
    "/usr/local/bin/choose-mirror": "0:0:755",
    "/usr/local/bin/Installation_guide": "0:0:755",
    "/usr/local/bin/livecd-sound": "0:0:755",
    # The Calamares launcher the Openbox autostart runs on live login. archiso
    # NORMALIZES overlay file modes when it packs the squashfs -- only paths
    # listed here keep an explicit mode. Without this entry the wrapper ships
    # 0644 (non-executable), the autostart's `[ -x ... ]` guard is false, and
    # Calamares never auto-launches. THIS is what breaks the live installer.
    "/usr/local/bin/azarch-install": "0:0:755",
    "/root/azarch/setup-locale.sh": "0:0:755",
    "/etc/systemd/system/locale-setup.service": "0:0:644",
    "/root/azarch/setup-pkgs.sh": "0:0:755",
    "/etc/systemd/system/pkgs-setup.service": "0:0:644",
}


def profiledef_sh() -> str:
    bootmodes = " ".join(f"'{m}'" for m in BOOTMODES)
    perms = "\n".join(f'  ["{p}"]="{v}"' for p, v in FILE_PERMISSIONS.items())
    return f"""\
#!/usr/bin/env bash
# shellcheck disable=SC2034
#
# Generated by azarch.config.profile -- edit the Python, not this file.

iso_name="{ISO_NAME}"
iso_label="AZARCH_$(date --date="@${{SOURCE_DATE_EPOCH:-$(date +%s)}}" +%Y%m)"
iso_publisher="{ISO_PUBLISHER}"
iso_application="{ISO_APPLICATION}"
iso_version="$(date --date="@${{SOURCE_DATE_EPOCH:-$(date +%s)}}" +%Y.%m.%d)"
install_dir="{INSTALL_DIR}"
buildmodes=('iso')
bootmodes=({bootmodes})
arch="x86_64"
cow_spacesize="4G"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"

### This line fixes an odd bug that appeared out of nowhere
### \"\"\"FATAL ERROR: xz uncompress failed with error code 9\"\"\"
airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '15')
###

bootstrap_tarball_compression=('zstd' '-c' '-T0' '--auto-threads=logical' '--long' '-19')
file_permissions=(
{perms}
)
"""
