"""Thunar UI-string overrides via a gettext .mo catalog (PROMPT batch items 3, 7, 8-wording).

A few Thunar menu labels are HARDCODED gettext strings in the binary (there is no config /
xfconf / uca.xml lever for them -- verified against the Thunar 4.20 source). The supported,
stable way to change them is a gettext message catalog: Thunar calls
`bindtextdomain("thunar", "/usr/share/locale")` and every menu label goes through `gettext()`,
so a `thunar.mo` under the ACTIVE locale's LC_MESSAGES dir that maps the exact msgid to our
wording wins -- no fighting hardcoded C++ (this is GTK/gettext, the intended mechanism).

WHAT WE OVERRIDE (each msgid is the EXACT string from the 4.20 binary; the mnemonic `_` and the
`...` ellipsis are part of the msgid and must match byte-for-byte or gettext falls through to
the original):

  * "Places"            -> "Home Directory"   (batch item 3: rename the shortcuts-pane header)
  * '_Open With "%s"'   -> "_Edit with %s"     (batch item 7: the built-in default-opener at the
        top of the context menu -- for a text file whose default is gedit it reads
        `Open With "gedit"`. Overriding the format to `Edit with %s` makes that top item read
        `Edit with gedit` with NO quotes. Our own uca "Edit with gedit" duplicate is DROPPED
        (see actions.py) so exactly ONE such entry remains, at the top. The images-only "Edit
        with gimp" uca action stays.)
  * "Create _Folder..." -> "Create New _Folder..."    (batch item 8 wording)
  * "Create _Document"  -> "Create New _Document..."   (batch item 8 wording; the base label
        carries no ellipsis in the msgid, we add it to match "Create New Folder...")

WHY THIS WORKS UNDER en_US (the session locale). The Az'arch session runs LANG=en_US.UTF-8
(modifications/calamares/locale). A common myth is that gettext returns English msgids verbatim
and ignores catalogs for English; that is TRUE ONLY for the C/POSIX locale. For a REAL generated
locale (en_US.UTF-8, en_GB.UTF-8 -- both generated by locale-gen here) glibc's gettext DOES
consult the catalog. VERIFIED on the build host with the real C `gettext(1)` tool: with the
catalog at .../en_US/LC_MESSAGES/thunar.mo, `LANGUAGE=en_US gettext -d thunar -s "Places"`
returns "Home Directory". So we ship the SAME catalog under BOTH en_US and en_GB (the two
locales the ISO generates -- en_GB is the LC_TIME date locale) and it takes effect with the
session's existing LANG; no LANGUAGE tricks, no whole-desktop locale change.

THE .mo IS GENERATED IN PURE PYTHON (mo_bytes()) -- the standard GNU .mo binary format (a tiny,
well-specified table of msgid/msgstr offsets). No external `msgfmt` dependency, deterministic
(so a test can pin the bytes), and it slots into the emit machinery as a binary blob.

compiler._emit_apps ships the .mo as a ROOT-owned system file at each locale path (it is a
system locale catalog, not a per-user dotfile) -- so every user on the installed system gets
the relabelled Thunar. (Delivered via the "mo" plan-entry kind that compiler writes verbatim.)
"""

from __future__ import annotations

import struct

# The locales the Az'arch ISO generates (modifications/calamares/locale): en_US.UTF-8 is the
# display language, en_GB.UTF-8 the LC_TIME date locale. Ship the override catalog under BOTH
# so whichever LC_MESSAGES is in effect finds it. The catalog dir is the standard system path
# Thunar's bindtextdomain uses.
LOCALES: tuple[str, ...] = ("en_US", "en_GB")
TEXTDOMAIN = "thunar"


def mo_path(locale: str) -> str:
    """Absolute system path of the Thunar override catalog for a locale (the standard
    /usr/share/locale/<locale>/LC_MESSAGES/<domain>.mo Thunar's bindtextdomain reads)."""
    return f"/usr/share/locale/{locale}/LC_MESSAGES/{TEXTDOMAIN}.mo"


# The exact msgid -> our-wording map. Keys are the EXACT strings from the Thunar 4.20 binary
# (mnemonics and ellipses included) -- a byte mismatch means gettext falls through to the
# original, so these must not be "cleaned up". VERIFIED via `strings /usr/bin/thunar`.
OVERRIDES: dict[str, str] = {
    "Places": "Home Directory",
    '_Open With "%s"': "_Edit with %s",
    "Create _Folder...": "Create New _Folder...",
    "Create _Document": "Create New _Document...",
}


def mo_bytes() -> bytes:
    """Return the GNU .mo binary catalog for OVERRIDES (domain `thunar`).

    Implements the documented GNU MO format (little-endian): magic 0x950412de, revision 0,
    a count N, the offsets of the msgid and msgstr string tables, then N (length, offset)
    pairs for the sorted msgids followed by N pairs for the msgstrs, then the string data.
    msgids MUST be sorted (gettext binary-searches them). A leading empty-string entry with a
    minimal header is conventional; we include it so the catalog is well-formed and carries the
    charset. Pure standard library (struct), deterministic -- a test pins the round-trip."""
    # The empty msgid maps to the catalog header (charset etc.), per the GNU format.
    header = "Content-Type: text/plain; charset=UTF-8\n"
    entries = {"": header}
    entries.update(OVERRIDES)
    # Sort by msgid bytes (gettext requires sorted keys for its binary search).
    keys = sorted(entries.keys(), key=lambda k: k.encode("utf-8"))
    ids = b""
    strs = b""
    id_table: list[tuple[int, int]] = []   # (length, offset) into the ids blob
    str_table: list[tuple[int, int]] = []
    for k in keys:
        kb = k.encode("utf-8")
        vb = entries[k].encode("utf-8")
        id_table.append((len(kb), len(ids)))
        ids += kb + b"\x00"                 # NUL-terminated (length excludes the NUL)
        str_table.append((len(vb), len(strs)))
        strs += vb + b"\x00"
    n = len(keys)
    # Layout: 7 uint32 header, then the two tables (each n*2 uint32), then the string blobs.
    header_size = 7 * 4
    id_table_off = header_size
    str_table_off = id_table_off + n * 8
    ids_off = str_table_off + n * 8
    strs_off = ids_off + len(ids)
    out = bytearray()
    out += struct.pack("<Iiiiiii",
                       0x950412de,   # magic
                       0,            # file format revision
                       n,            # number of strings
                       id_table_off, # offset of table with original strings
                       str_table_off,# offset of table with translated strings
                       0,            # size of hashing table (unused)
                       0)            # offset of hashing table (unused)
    for length, off in id_table:
        out += struct.pack("<II", length, ids_off + off)
    for length, off in str_table:
        out += struct.pack("<II", length, strs_off + off)
    out += ids
    out += strs
    return bytes(out)
