"""Thunar sidebar shortcuts -- ~/.config/gtk-3.0/bookmarks, built from home_directory.

Thunar's shortcuts pane reads the GTK bookmarks file (~/.config/gtk-3.0/bookmarks, the
freedesktop GTK bookmarks format Nautilus/Thunar/PCManFM all share -- verified: Thunar 4.20
references `.gtk-bookmarks` / the gtk-3.0 bookmarks path). Each line is:

    file:///absolute/path   Optional Label

We generate ONE bookmark per home_directory sidebar entry, so the sidebar lists EXACTLY the
Az'arch layout set (Desktop, Downloads, Vault, Documents, Ignore, Music, Pictures, Projects,
Videos, Trash, Cache, Config, Bashrc, Local) in that order -- the SAME set as the on-disk
home layout, because both come from modifications/home_directory (its single source of truth).
Add a folder there and it appears both on disk and here.

RESOLVED TARGETS (PROMPT task 2). Each bookmark points at the RESOLVED path, not a symlink:
home_directory.sidebar_entries() already resolves the convenience symlinks (Config ->
/home/main/.config, Trash -> /home/main/.local/share/Trash/files, ...). So clicking a
shortcut enters the real directory and Thunar's (text-entry) location bar shows the ACTUAL
path, not the /home/main/Config symlink path. The label is forced to the Az'arch name (e.g.
"Config"), so the sidebar reads "Config" even though it points at .config.

The built-in Places/Devices/Network clutter is hidden separately (settings.HIDDEN_BOOKMARKS /
HIDDEN_DEVICES); this file only ADDS our shortcuts. Shipped as a HOME file (owner "home",
skel-mirrored) by compiler._emit_apps.

Pure standard library (returns a string).
"""

from __future__ import annotations

from modifications import home_directory

# The live user's home (matches openbox.HOME / the airootfs /home/main tree).
HOME = "/home/main"

# Where GTK (and thus Thunar's shortcuts pane) reads the bookmarks. XDG_CONFIG_HOME defaults
# to ~/.config, which the OpenBox session exports.
GTK_BOOKMARKS_PATH = f"{HOME}/.config/gtk-3.0/bookmarks"


# Labels Thunar ALREADY provides as a built-in "Places" shortcut at the SAME resolved path,
# so adding our own bookmark for them would DUPLICATE the entry in the side pane (verified: a
# GTK bookmark for file:///home/main/Desktop shows a second "Desktop" next to the built-in
# one). We therefore SKIP these here and let Thunar's built-in shortcut serve them:
#   * Desktop -- the built-in "Desktop" place points at ~/Desktop (our exact resolved target),
#     and its URI (file://$HOME/Desktop) is identical to what our bookmark would use, so it
#     cannot be hidden without also hiding our bookmark. Keep the built-in, skip our duplicate.
# Trash is NOT skipped: the built-in Trash uses the trash:/// URI, so our resolved-path Trash
# bookmark (file://.../Trash/files, which the PROMPT asks for) is a DIFFERENT shortcut -- the
# built-in trash:/// one is hidden via settings.HIDDEN_BOOKMARKS, leaving only ours.
_BUILTIN_PROVIDED = frozenset({"Desktop"})

# NO "Home Directory" bookmark. The user asked for it to be DELETED from the Places sidebar
# ("has 'Home Directory', just delete it, we dont actually need it there is a home button").
# So we neither ship a "Home Directory" bookmark nor keep the built-in username Home: the
# built-in Home shortcut (file:///home/main) is still hidden via settings.HIDDEN_BOOKMARKS, and
# no replacement bookmark is added here. The sidebar therefore starts straight at the layout
# folders (Downloads, Vault, ...). Thunar's own Home toolbar button covers navigating home.


def _file_uri(abs_path: str) -> str:
    """Return the file:// URI for an absolute path. The paths here are plain home paths
    (ASCII, no spaces), so a simple prefix is correct and readable; kept explicit so a
    reviewer sees the exact bookmark form Thunar parses."""
    return f"file://{abs_path}"


def gtk_bookmarks() -> str:
    """Return ~/.config/gtk-3.0/bookmarks -- one `file:///... Label` line per
    home_directory sidebar entry (EXCEPT the few Thunar already provides as built-in places,
    see _BUILTIN_PROVIDED), in display order, each pointing at the RESOLVED target with the
    Az'arch label. Together with the built-in Home/Desktop (kept) and the hidden built-in
    clutter (settings.HIDDEN_*), this makes the side pane show exactly the Az'arch layout set.

    NOTE: the GTK bookmarks format has NO comment syntax (every non-blank line is parsed as a
    bookmark), so unlike the other config files this one carries no `# generated by` banner --
    a comment line would show up as a bogus sidebar entry."""
    # No "Home Directory" bookmark -- the user deleted it from the sidebar (see the module note);
    # the list starts straight at the layout folders.
    lines: list[str] = []
    for label, target in home_directory.sidebar_entries():
        if label in _BUILTIN_PROVIDED:
            continue  # Thunar's built-in place already covers this at the same path.
        lines.append(f"{_file_uri(target)} {label}")
    return "\n".join(lines) + "\n"
