"""
spec_render -- assemble the General spec (documentation/SPECIFICATIONS_GENERAL.md)
from resolved data, the per-package tags (spec_classify) and the subsystem prose
(spec_content).

This is the general / developer-facing document: at-a-glance facts, what Az'arch
changes on top of stock Arch, and the subsystem-by-subsystem breakdown of what
the software is. The full base->top dependency graph -- the base/leaf tiers, the
per-package manifest table and the complete package appendix -- deliberately does
NOT live here; that is the companion graph image (spec_svg). Keeping the two
apart is the whole point: this file is prose + curated tables, the SVG is the
graph.
"""

import sys

import spec_content as C
import spec_classify as K

def _warn(msg):
    print(f"[render] WARN: {msg}", file=sys.stderr)


class Doc:
    def __init__(self):
        self.parts = []

    def w(self, s=""):
        self.parts.append(s)

    def text(self):
        return "\n".join(self.parts) + "\n"


def _pkg_version(packages, name):
    rec = packages.get(name)
    return rec["version"] if rec else "?"


def _versions_for_label(packages, label, closure):
    """Render the version cell for a possibly-'a / b' label, warning on misses."""
    names = [p.strip() for p in label.split("/")]
    versions = []
    for name in names:
        if name in packages and name in closure:
            versions.append(_pkg_version(packages, name))
        else:
            _warn(f"subsystem lists '{name}' which is not in the resolved closure")
            versions.append("?")
    if len(set(versions)) == 1:
        return versions[0]
    return " / ".join(versions)


def render(packages, resolved, tiers, tags, glance, svg_rel):
    # This document is the general / components view: at-a-glance, what Az'arch
    # changes, and the subsystem breakdown. The full dependency-graph tiers (base
    # tier, leaves, manifest table, full package appendix) live in the companion
    # graph image, so they are deliberately NOT rendered here.
    closure = resolved["closure"]
    roots = resolved["roots"]

    def cat(p):
        return tags[p]["category"]

    d = Doc()
    d.w("# Az'arch -- General Specification")
    d.w()
    d.w(f"General and developer-facing spec of the Az'arch distribution. The full "
        f"base->top dependency graph (kernel up to leaf apps, tiered), with every "
        f"component, lives in the companion image [`{svg_rel}`]({svg_rel}); this "
        f"document is the prose and tables a developer of the distro actually "
        f"needs. Generated by `scripts/pull_specifications.sh` from the official "
        f"Arch `core`/`extra`/`multilib` databases.")
    d.w()
    d.w("---")
    d.w()

    # 1. At a glance ---------------------------------------------------------
    d.w("## 1. At a glance")
    d.w()
    d.w(f"- **Base distribution:** {glance['base']}")
    d.w(f"- **Desktop:** {glance['desktop']}")
    d.w(f"- **Kernel:** `linux` {glance['kernel']}")
    d.w(f"- **Init:** `systemd` {glance['init']}")
    d.w(f"- **Display manager / session:** {glance['dm']}")
    d.w(f"- **ISO versioning:** {glance['iso_version']}")
    d.w(f"- **Live-session writable RAM (`cow_spacesize`):** {glance['ram']}")
    d.w(f"- **Purpose:** {glance['purpose']}")
    d.w()
    d.w("| Metric | Value |")
    d.w("|---|---:|")
    dupes = glance['raw_lines'] - glance['tokens']
    dup_note = f"; {dupes} duplicate line{'s' if dupes != 1 else ''} de-duped" if dupes else ""
    d.w(f"| Explicit manifest entries | {glance['tokens']} "
        f"({glance['raw_lines']} non-comment lines{dup_note}) |")
    d.w(f"| Explicit entries incl. group members (e.g. `xorg`) | {len(roots)} |")
    d.w(f"| **Full package set (transitive closure)** | **{len(closure)}** |")
    d.w(f"| &nbsp;&nbsp;from `core` / `extra` / `multilib` | "
        f"{glance['by_repo']['core']} / {glance['by_repo']['extra']} / "
        f"{glance['by_repo']['multilib']} |")
    d.w(f"| Edition: Az'arch Component / Stock Arch | "
        f"{glance['azarch']} / {glance['stock']} |")
    d.w(f"| Top / leaf packages (nothing depends on them) | {len(tiers['leaves'])} |")
    d.w(f"| Base / sink packages (depend on nothing else in the set) | "
        f"{len(tiers['bases'])} |")
    d.w(f"| Deepest dependency chain (leaf -> base) | {tiers['max_height']} hops |")
    d.w(f"| Total installed size of the package set | {glance['size']} |")
    d.w()
    d.w("**Edition tags** (used throughout, and marked on the SVG):")
    d.w()
    d.w("| Tag | Meaning |")
    d.w("|---|---|")
    d.w("| `az'arch` | **Az'arch Component** -- in the package set **only** "
        "because Az'arch added it on top of the stock archiso `releng` baseline "
        "(a chosen application, or a dependency that exists purely to support "
        "one). The subset Az'arch also rebrands/themes/removes is called out in "
        "section 3. |")
    d.w("| `stock` | **Stock Arch** -- already pulled in by the stock archiso "
        "`releng` install medium; Az'arch inherits it whether it adds anything "
        "or not. |")
    d.w()
    d.w("---")
    d.w()

    # 2. Network endpoints ---------------------------------------------------
    d.w("## 2. Network endpoints -- what the distro contacts")
    d.w()
    d.w("Every external host and service the distribution talks to: where it "
        "downloads packages from, how it resolves the timezone and locale, and "
        "what it pings. Read live from the build config "
        "(`libraries/azarch/config/*.py`), so this list cannot drift from what the "
        "ISO actually does. The system is designed to work fully offline; these "
        "are the endpoints used **when a network is available**.")
    d.w()
    d.w("| Endpoint | Purpose | Where / notes |")
    d.w("|---|---|---|")
    for endpoint, purpose, context in glance["endpoints"]:
        d.w(f"| `{endpoint}` | {purpose} | {context} |")
    d.w()
    d.w("Notes for a developer:")
    d.w()
    d.w("- **Package mirrors** are hard-coded for the *build* (host-independent so "
        "the ISO builds identically on Arch, Manjaro or Docker); the *installed* "
        "system uses the standard Arch `mirrorlist`. The offline `file://` repo is "
        "the baked-in package cache used when no mirror is reachable.")
    d.w("- **Timezone / locale / keyboard** are auto-detected on first boot from a "
        "geo-IP lookup; if that host is unreachable the defaults (`en_US.UTF-8`, "
        "`us`) apply. Change the provider in `libraries/azarch/config/locale.py`.")
    d.w("- **Time sync** uses systemd-timesyncd's default NTP servers, enabled only "
        "after the connectivity probe succeeds.")
    d.w()
    d.w("---")
    d.w()

    # 3. Az'arch modifications ----------------------------------------------
    d.w("## 3. What Az'arch changes on top of Arch")
    d.w()
    d.w("Every package comes unmodified from the official Arch repos; Az'arch's "
        "identity is *curation* (which packages ship, chosen in `libraries/data/"
        "packages.x86_64` on top of the stock archiso baseline) plus "
        "*configuration and branding* on the packages below. Note this is a "
        "narrower set than the **Az'arch Component** edition: a package can be an "
        "Az'arch Component (added by Az'arch) without being reconfigured, and a "
        "**Stock Arch** package (e.g. `pacman`, `systemd`) can still carry an "
        "Az'arch config change. The table below lists only the packages that "
        "carry Az'arch-specific changes -- grounded in the build's own config "
        "modules (`libraries/azarch/config/*.py`).")
    d.w()
    d.w("| Package | Version | Category | What Az'arch does | Shipped? |")
    d.w("|---|---|---|---|---|")
    for p in sorted(K.AZARCH_CONFIGURED):
        if p not in closure:
            continue
        shipped = "removed" if tags[p]["removed"] else "yes"
        d.w(f"| `{p}` | {_pkg_version(packages, p)} | {cat(p)} | "
            f"{tags[p]['azarch_note']} | {shipped} |")
    d.w()
    d.w("---")
    d.w()

    # 4. Subsystems ---------------------------------------------------------
    d.w("## 4. Subsystems -- what the software actually is")
    d.w()
    d.w("The key packages grouped by real function, with concrete technical "
        "capabilities and real versions. (The full base->top dependency graph and "
        "the complete package list are in the companion graph image, not here.)")
    d.w()
    for _key, title, prose, rows in C.SUBSYSTEMS:
        d.w(f"### {title}")
        d.w()
        d.w(prose)
        d.w()
        d.w("| Package | Version | Capability |")
        d.w("|---|---|---|")
        for label, capability in rows:
            version = _versions_for_label(packages, label, closure)
            tick = " / ".join(f"`{x.strip()}`" for x in label.split("/"))
            d.w(f"| {tick} | {version} | {capability} |")
        d.w()

    return d.text()
