"""
spec_render -- assemble documentation/SPECIFICATIONS.md from resolved graph data,
the per-package tags (spec_classify) and the subsystem prose (spec_content).

Practical, low-yap: the document is tables you can grep, diff and act on when
adding or removing packages. Every package row carries its edition (stock-Arch
dep / Arch package Az'arch selected / package Az'arch modifies) and a
human-language category. The navigable layered view is the companion SVG
(spec_svg); this file cross-references it but does not duplicate the ASCII art.
"""

import sys

import spec_content as C
import spec_classify as K

REPOS = ("core", "extra", "multilib")

# short edition labels used in the tables
ED_LABEL = {
    "az'arch": "az'arch",
    "arch-selected": "arch-sel",
    "arch-dep": "arch-dep",
}


def _warn(msg):
    print(f"[render] WARN: {msg}", file=sys.stderr)


def human_size(num):
    b = float(num)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if b < 1024:
            return f"{b:.0f} {unit}" if unit == "B" else f"{b:.1f} {unit}"
        b /= 1024
    return f"{b:.1f} PiB"


class Doc:
    def __init__(self):
        self.parts = []

    def w(self, s=""):
        self.parts.append(s)

    def text(self):
        return "\n".join(self.parts) + "\n"


def _pkg_version(packages, name):
    rec = packages.get(name)
    return rec["version"] if rec else "?"


def _versions_for_label(packages, label, closure):
    """Render the version cell for a possibly-'a / b' label, warning on misses."""
    names = [p.strip() for p in label.split("/")]
    versions = []
    for name in names:
        if name in packages and name in closure:
            versions.append(_pkg_version(packages, name))
        else:
            _warn(f"subsystem lists '{name}' which is not in the resolved closure")
            versions.append("?")
    if len(set(versions)) == 1:
        return versions[0]
    return " / ".join(versions)


def render(packages, resolved, tiers, tags, glance, svg_rel):
    manifest_map = resolved["manifest_map"]
    closure = resolved["closure"]
    roots = resolved["roots"]

    outdeg = tiers["outdeg"]
    indeg = tiers["indeg"]
    trans_dep = tiers["trans_dependents"]
    trans_deps = tiers["trans_deps"]

    manifest_tokens = list(manifest_map)

    def ed(p):
        return ED_LABEL[tags[p]["edition"]]

    def cat(p):
        return tags[p]["category"]

    d = Doc()
    d.w("# Az'arch -- Distribution Specification")
    d.w()
    d.w(f"Generated by `scripts/pull_specifications.sh` from the official Arch "
        f"`core`/`extra`/`multilib` databases. Companion image: "
        f"[`{svg_rel}`]({svg_rel}) (layered kernel-to-apps graph).")
    d.w()
    d.w("---")
    d.w()

    # 1. At a glance ---------------------------------------------------------
    d.w("## 1. At a glance")
    d.w()
    d.w(f"- **Base distribution:** {glance['base']}")
    d.w(f"- **Desktop:** {glance['desktop']}")
    d.w(f"- **Kernel:** `linux` {glance['kernel']}")
    d.w(f"- **Init:** `systemd` {glance['init']}")
    d.w(f"- **Display manager / session:** {glance['dm']}")
    d.w(f"- **ISO versioning:** {glance['iso_version']}")
    d.w(f"- **Live-session writable RAM (`cow_spacesize`):** {glance['ram']}")
    d.w(f"- **Purpose:** {glance['purpose']}")
    d.w()
    d.w("| Metric | Value |")
    d.w("|---|---:|")
    d.w(f"| Explicit manifest entries | {glance['tokens']} "
        f"({glance['raw_lines']} lines; `unzip` listed twice) |")
    d.w(f"| Explicit entries incl. group members (`xorg`+`plasma`) | {len(roots)} |")
    d.w(f"| **Full package set (transitive closure)** | **{len(closure)}** |")
    d.w(f"| &nbsp;&nbsp;from `core` / `extra` / `multilib` | "
        f"{glance['by_repo']['core']} / {glance['by_repo']['extra']} / "
        f"{glance['by_repo']['multilib']} |")
    d.w(f"| Edition: Az'arch-modified / selected / dependency | "
        f"{glance['azarch']} / {glance['selected']} / {glance['dep']} |")
    d.w(f"| Top / leaf packages (nothing depends on them) | {len(tiers['leaves'])} |")
    d.w(f"| Base / sink packages (depend on nothing else in the set) | "
        f"{len(tiers['bases'])} |")
    d.w(f"| Deepest dependency chain (leaf -> base) | {tiers['max_height']} hops |")
    d.w(f"| Total installed size of the package set | {glance['size']} |")
    d.w()
    d.w("**Edition tags** (used throughout, and marked on the SVG):")
    d.w()
    d.w("| Tag | Meaning |")
    d.w("|---|---|")
    d.w("| `az'arch` | Az'arch modifies this package: ships config, rebrands, "
        "themes, or removes it. See section 2. |")
    d.w("| `arch-sel` | Stock Arch package, but **explicitly listed** in "
        "`packages.x86_64` -- an Az'arch curation choice. |")
    d.w("| `arch-dep` | Stock Arch package pulled in **only** as a transitive "
        "dependency; not chosen directly. |")
    d.w()
    d.w("---")
    d.w()

    # 2. Az'arch modifications ----------------------------------------------
    d.w("## 2. What Az'arch changes on top of Arch")
    d.w()
    d.w("Every package is stock Arch from the official repos; Az'arch's identity "
        "is *curation* (which packages, section 6) plus *configuration and "
        "branding* on the packages below. These are the only packages that carry "
        "Az'arch-specific changes -- grounded in the build's own config modules "
        "(`libraries/azarch/config/*.py`).")
    d.w()
    d.w("| Package | Version | Category | What Az'arch does | Shipped? |")
    d.w("|---|---|---|---|---|")
    for p in sorted(K.AZARCH_CONFIGURED):
        if p not in closure:
            continue
        shipped = "removed" if tags[p]["removed"] else "yes"
        d.w(f"| `{p}` | {_pkg_version(packages, p)} | {cat(p)} | "
            f"{tags[p]['azarch_note']} | {shipped} |")
    d.w()
    d.w("---")
    d.w()

    # 3. Base tier ----------------------------------------------------------
    bases = sorted(tiers["bases"], key=lambda p: (-trans_dep[p], p))
    d.w("## 3. Base tier -- the bottom of the graph")
    d.w()
    d.w(f"The **{len(bases)}** sinks of the dependency graph: they pull in nothing "
        "else from the set. Sorted by how many packages ultimately depend on them "
        "(the most load-bearing first).")
    d.w()
    d.w("| Package | Version | Repo | Edition | Category | Depended on by | "
        "Installed | What it is |")
    d.w("|---|---|---|---|---|---:|---:|---|")
    for p in bases:
        r = packages[p]
        d.w(f"| `{p}` | {r['version']} | {r['repo']} | {ed(p)} | {cat(p)} | "
            f"{trans_dep[p]} | {human_size(r['isize'])} | {r['desc']} |")
    d.w()
    d.w("---")
    d.w()

    # 4. Top tier -----------------------------------------------------------
    leaves = sorted(tiers["leaves"], key=lambda p: (-trans_deps[p], p))
    d.w("## 4. Top tier -- the leaves")
    d.w()
    d.w(f"The **{len(leaves)}** leaves: nothing in the set depends on them. Remove "
        "any one and nothing else breaks -- only that package and any deps that "
        "become orphaned go away. \"Pulls in\" is the transitive dependency count "
        "each leaf drags in behind it. **This is the tier to edit when adding or "
        "removing applications.**")
    d.w()
    d.w("| Package | Version | Repo | Edition | Category | Pulls in | Installed | "
        "What it is |")
    d.w("|---|---|---|---|---|---:|---:|---|")
    for p in leaves:
        r = packages[p]
        d.w(f"| `{p}` | {r['version']} | {r['repo']} | {ed(p)} | {cat(p)} | "
            f"{trans_deps[p]} | {human_size(r['isize'])} | {r['desc']} |")
    d.w()
    d.w("---")
    d.w()

    # 5. Subsystems ---------------------------------------------------------
    d.w("## 5. Subsystems -- what the software actually is")
    d.w()
    d.w("The key packages grouped by real function, with concrete technical "
        "capabilities and real versions.")
    d.w()
    for _key, title, prose, rows in C.SUBSYSTEMS:
        d.w(f"### {title}")
        d.w()
        d.w(prose)
        d.w()
        d.w("| Package | Version | Capability |")
        d.w("|---|---|---|")
        for label, capability in rows:
            version = _versions_for_label(packages, label, closure)
            tick = " / ".join(f"`{x.strip()}`" for x in label.split("/"))
            d.w(f"| {tick} | {version} | {capability} |")
        d.w()
    d.w("---")
    d.w()

    # 6. Manifest tier ------------------------------------------------------
    d.w("## 6. Explicit manifest -- the curation source of truth")
    d.w()
    d.w("`libraries/data/packages.x86_64`: the packages the ISO explicitly "
        "requests. Everything else in the graph is pulled in as a dependency. "
        "Edit this file to add/remove packages.")
    d.w()
    d.w("| # | Manifest entry | Resolves to | Edition | Category | Tier | Version |")
    d.w("|---:|---|---|---|---|---|---|")
    for i, tok in enumerate(manifest_tokens, 1):
        v = manifest_map[tok]
        if v["kind"] == "group":
            d.w(f"| {i} | `{tok}` | *group -> {len(v['members'])} pkgs* | -- | -- | "
                "root (group) | -- |")
        elif v["kind"] == "package":
            res = v["resolved"]
            tier = []
            if indeg.get(res) == 0:
                tier.append("top/leaf")
            if outdeg.get(res) == 0:
                tier.append("base/sink")
            if not tier:
                tier.append("interior")
            d.w(f"| {i} | `{tok}` | `{res}` | {ed(res)} | {cat(res)} | "
                f"{', '.join(tier)} | {_pkg_version(packages, res)} |")
        else:
            d.w(f"| {i} | `{tok}` | UNRESOLVED | -- | -- | -- | -- |")
    d.w()
    d.w("---")
    d.w()

    # 7. Appendix -----------------------------------------------------------
    d.w("## 7. Appendix -- full resolved package set")
    d.w()
    d.w(f"All **{len(closure)}** packages in the transitive closure, with edition, "
        "category, version and repo. Format: `EDITION  category  name version "
        "[repo]`. Grep it: e.g. `grep az'arch` for Az'arch-modified packages, or "
        "`grep 'Networking'` for the network stack.")
    d.w()
    d.w("```text")
    ed_pad = max(len(ED_LABEL[tags[p]["edition"]]) for p in closure)
    cat_pad = max(len(cat(p)) for p in closure)
    for p in sorted(closure):
        r = packages[p]
        d.w(f"{ed(p):<{ed_pad}}  {cat(p):<{cat_pad}}  {p} {r['version']} [{r['repo']}]")
    d.w("```")

    return d.text()
