#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# yay wrapper to automatically add --overwrite '*'
yay() {
    if [[ $1 == "-S" ]]; then
        shift
        command yay -S --overwrite '*' "$@"
    else
        command yay "$@"
    fi
}

