"""GIMP configuration modification -- skip the first-run / introduction dialogs.

GIMP (shipped as the `gimp` package) greets a fresh profile with an introduction message
Az'arch wants gone from the very first launch, exactly the way modifications/libreoffice.py
suppresses LibreOffice's first-run popups and modifications/vlc.py suppresses VLC's privacy
dialog:

  * "Tip of the Day"   -- the tips dialog shown on start (config-suppressible: show-tips no).
  * "Welcome to GIMP"  -- the fresh-profile welcome dialog (show-welcome-dialog no).

GIMP LOADS NORMALLY. This is a CONFIG-ONLY modification: it ships a gimprc and nothing else.
There is deliberately NO preload / warm-start / prewarming machinery (an earlier attempt at
that was reverted -- GIMP opens like any other application), NO .desktop Exec override, and
NO window helper. Opening GIMP starts a plain, stock `gimp`; only the intro dialogs are
turned off via GIMP's own configuration.

SCOPE / CAVEAT (honest about what config-only can and cannot do). The gimprc reliably turns
off the Tip-of-the-Day dialog and the fresh-profile welcome. GIMP 3.2 ALSO shows a
version-gated "Welcome to GIMP <ver>" ("what's new") dialog once after a version update, and
that one is a SEPARATE top-level window that `(show-welcome-dialog no)` was observed NOT to
suppress -- previously it was closed by an X11 helper. That helper was part of the
preload/winmove machinery the user reverted (GIMP must load normally), so it is intentionally
NOT reintroduced here: config-only is the deliberate limit. The version-update dialog may
therefore still appear once after a GIMP upgrade; the routine first-run intro dialogs do not.

HOW (a preseeded gimprc, the supported analog of libreoffice's registrymodifications.xcu).
GIMP reads per-user options from ~/.config/GIMP/<ver>/gimprc, one `(key value)` s-expression
per line, merged OVER GIMP's built-in defaults (every other option stays stock). GIMP rewrites
this file itself on exit but preserves these keys, so the shipped copy is just the initial
seed. The two keys that turn the intro dialogs off:

  * (show-welcome-dialog no)  -- do not show the "Welcome to GIMP" dialog.
  * (show-tips no)            -- do not show the "Tip of the Day" dialog.

WHERE IT GOES. ~/.config/GIMP/3.2/gimprc for the live user (compiler.py chowns it 1000:998
and mirrors it into /etc/skel so a Calamares-created user inherits the same quiet first run).
The version dir is GIMP 3.2's REAL per-user config dir: `3.2`, NOT `3.0` (GIMP 3.2 reads
~/.config/GIMP/3.2/gimprc; a 3.0 dir is ignored). GIMP_VERSION_DIR pins it.

Pure standard library (returns a string). compiler.py iterates emit_plan() exactly like
modifications/libreoffice and modifications/vlc -- one HOME file, owner="home".
"""

from __future__ import annotations

# The live user's home (matches openbox.HOME / the airootfs /home/main tree).
HOME = "/home/main"

# GIMP 3.2's REAL per-user config dir is versioned `3.2` (verified: ~/.config/GIMP/3.0/
# gimprc is ignored, ~/.config/GIMP/3.2/gimprc is read). Pinned as the single source of
# truth for the path; emit_plan() ships the file here and compiler.py mirrors it into
# /etc/skel. XDG_CONFIG_HOME defaults to ~/.config, which the OpenBox session sets.
GIMP_VERSION_DIR = "3.2"
GIMPRC_PATH = f"{HOME}/.config/GIMP/{GIMP_VERSION_DIR}/gimprc"


def gimprc() -> str:
    """Return the seed gimprc that turns off GIMP's Tip-of-the-Day and fresh-profile welcome
    intro dialogs (see the module docstring for the version-update-dialog caveat).

    Only the two intro-suppressing keys are written; GIMP merges them over its built-in
    defaults, so every other option stays stock. Each line is a `(key value)` s-expression
    in GIMP's gimprc syntax. GIMP rewrites this file on exit but preserves these keys."""
    return """\
# Az'arch GIMP config -- turn off the first-run intro dialogs (Tip of the Day, and the
# fresh-profile Welcome). Generated by modifications/gimp.py (edit the Python, not this
# file). GIMP reads these keys over its built-in defaults; every other option is left
# exactly as GIMP ships it, and GIMP rewrites this file when an option changes. GIMP itself
# loads normally -- this only turns off the intro dialogs, it does not preload or warm GIMP.
# (GIMP's version-update "Welcome to GIMP <ver>" dialog is a separate window config alone
# may not suppress; the X11 closer for it was removed with the reverted preload -- see the
# module docstring.)
(show-welcome-dialog no)
(show-tips no)
"""


# --- Emit plan --------------------------------------------------------------
# Declarative map (builder -> dest -> mode -> owner), the same shape compiler.py iterates
# for modifications/libreoffice and modifications/openbox. One HOME file (owner="home"):
# compiler.py chowns it 1000:998 with the rest of /home/main AND mirrors it into /etc/skel
# so a Calamares-created user inherits the same quiet first run. Mode 0644 (plain config).
_CONF = 0o644


def emit_plan() -> list[dict]:
    """Return the emit plan for the GIMP override: a single HOME file at
    ~/.config/GIMP/3.2/gimprc.

    Shape matches libreoffice.emit_plan() (builder/dest/mode/owner) so compiler.py can emit
    it with the same loop (and skel-mirror the home file). Returns a FRESH dict so a caller
    cannot mutate module state."""
    return [
        {
            "builder": gimprc,
            "dest": GIMPRC_PATH,
            "mode": _CONF,
            "owner": "home",
        },
    ]
