"""LibreOffice configuration patch -- skip the first-run / introduction popups.

LibreOffice (the office suite Az'arch ships as `libreoffice-fresh`) greets a fresh profile
with a series of popups that Az'arch wants gone from the very first launch, exactly the way
patches/vlc.py suppresses VLC's first-run privacy dialog:

  * "Tip of the Day"        -- a modal shown on EVERY start until unticked.
  * The first-start wizard  -- LibreOffice's initial registration/online-setup run.
  * "What's New" / release-notes infobar on a new version.
  * The automatic online-update check popup.

HOW (a preseeded registrymodifications.xcu, the supported analog of the partial vlcrc).
LibreOffice persists user preference changes to a single XML file in the user profile,
~/.config/libreoffice/4/user/registrymodifications.xcu, as a list of <item oor:path=...>
entries -- each overriding ONE configuration node's default. We ship that file with only
the handful of nodes that turn the popups off; every other LibreOffice setting keeps its
default (LibreOffice merges these over the shipped registry, same as VLC merging vlcrc over
its defaults). LibreOffice REWRITES this file itself whenever the user changes a setting, so
our shipped copy is just the initial seed.

The node paths/keys below are the real oor config identifiers:
  * org.openoffice.Setup/Office/ooSetupInstCompleted = true  -- mark install setup done
  * org.openoffice.Setup/Office/FirstStartWizardCompleted = true -- skip the first-start run
  * org.openoffice.Office.Common/Misc/FirstRun = false       -- do not run the first-run job
  * org.openoffice.Office.Common/Misc/ShowTipOfTheDay = false -- no Tip of the Day modal
  * org.openoffice.Office.Common/Misc/ShowWhatsNew = false    -- no What's New screen
  * org.openoffice.Office.Jobs .../UpdateCheck/AutoCheckEnabled = false -- no update popup

WHERE IT GOES. ~/.config/libreoffice/4/user/registrymodifications.xcu for the live user
(compiler.py chowns it 1000:998 and mirrors it into /etc/skel so a Calamares-created user
inherits the same quiet first run). The "4" is LibreOffice's user-profile-version dir (the
current, long-stable profile layout the libreoffice-fresh build uses).

Pure standard library (returns a string). compiler.py iterates emit_plan() exactly like
patches/vlc -- one HOME file, owner="home".
"""

from __future__ import annotations

# The live user's home (matches openbox.HOME / the airootfs /home/main tree).
HOME = "/home/main"

# WHERE LIBREOFFICE READS ITS USER REGISTRY: ~/.config/libreoffice/4/user/
# registrymodifications.xcu (XDG_CONFIG_HOME defaults to ~/.config, which the OpenBox
# session sets). Single source of truth for the path; emit_plan() ships the file here and
# compiler.py mirrors it into /etc/skel.
REGMOD_PATH = f"{HOME}/.config/libreoffice/4/user/registrymodifications.xcu"


def registrymodifications_xcu() -> str:
    """Return the seed registrymodifications.xcu that disables LibreOffice's first-run and
    introduction popups (see the module docstring).

    Only the popup-suppressing nodes are written; LibreOffice merges them over its shipped
    registry defaults, so every other setting stays stock. Each <item> overrides one config
    node; the oor:path / prop name / value must match LibreOffice's schema or the item is
    ignored. Values are typed (xsi:type) as LibreOffice writes them: booleans as xsd:boolean."""
    return """\
<?xml version="1.0" encoding="UTF-8"?>
<!-- Az'arch LibreOffice overrides: skip the first-run and introduction popups (Tip of the
     Day, first-start wizard, What's New, online update check). Generated by
     patches/libreoffice.py (edit the Python, not this file). LibreOffice reads these nodes
     over its shipped registry defaults; every other setting is left exactly as LibreOffice
     ships it, and LibreOffice rewrites this file when a preference changes. -->
<oor:items xmlns:oor="http://openoffice.org/2001/registry"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <item oor:path="/org.openoffice.Setup/Office">
  <prop oor:name="ooSetupInstCompleted" oor:op="fuse">
   <value>true</value>
  </prop>
 </item>
 <item oor:path="/org.openoffice.Setup/Office">
  <prop oor:name="FirstStartWizardCompleted" oor:op="fuse">
   <value>true</value>
  </prop>
 </item>
 <item oor:path="/org.openoffice.Office.Common/Misc">
  <prop oor:name="FirstRun" oor:op="fuse">
   <value>false</value>
  </prop>
 </item>
 <item oor:path="/org.openoffice.Office.Common/Misc">
  <prop oor:name="ShowTipOfTheDay" oor:op="fuse">
   <value>false</value>
  </prop>
 </item>
 <item oor:path="/org.openoffice.Office.Common/Misc">
  <prop oor:name="ShowWhatsNew" oor:op="fuse">
   <value>false</value>
  </prop>
 </item>
 <item oor:path="/org.openoffice.Office.Jobs/Jobs/org.openoffice.Office.Jobs:Job['UpdateCheck']/Arguments">
  <prop oor:name="AutoCheckEnabled" oor:op="fuse">
   <value>false</value>
  </prop>
 </item>
</oor:items>
"""


# --- Emit plan --------------------------------------------------------------
# Declarative map (builder -> dest -> mode -> owner), the same shape compiler.py iterates
# for patches/vlc and patches/openbox. One HOME file (owner="home"): compiler.py chowns it
# 1000:998 with the rest of /home/main AND mirrors it into /etc/skel so a Calamares-created
# user inherits the same quiet first run. Mode 0644 (plain config data).
_CONF = 0o644


def emit_plan() -> list[dict]:
    """Return the emit plan for the LibreOffice override: a single HOME file at
    ~/.config/libreoffice/4/user/registrymodifications.xcu.

    Shape matches vlc.emit_plan() (builder/dest/mode/owner) so compiler.py can emit it with
    the same loop (and skel-mirror the home file). Returns a FRESH dict so a caller cannot
    mutate module state."""
    return [
        {
            "builder": registrymodifications_xcu,
            "dest": REGMOD_PATH,
            "mode": _CONF,
            "owner": "home",
        },
    ]
